// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    LBoundaryCanvas: typeof import('./src/components/L/plugins/LBoundaryCanvas.vue')['default']
    LConfigProvide: typeof import('./src/components/L/components/LConfigProvide.vue')['default']
    LFeatureGroup: typeof import('./src/components/L/components/LFeatureGroup.vue')['default']
    LFlyBounds: typeof import('./src/components/L/plugins/LFlyBounds.vue')['default']
    LFlyLatLng: typeof import('./src/components/L/plugins/LFlyLatLng.vue')['default']
    LFlyLatLngItem: typeof import('./src/components/L/plugins/LFlyLatLngItem.vue')['default']
    LGeoJson: typeof import('./src/components/L/components/LGeoJson.vue')['default']
    LIcon: typeof import('./src/components/L/components/LIcon.vue')['default']
    LLayerGroup: typeof import('./src/components/L/components/LLayerGroup.vue')['default']
    LMap: typeof import('./src/components/L/components/LMap.vue')['default']
    LMarker: typeof import('./src/components/L/components/LMarker.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    LPopup: typeof import('./src/components/L/components/LPopup.vue')['default']
    LRenderer: typeof import('./src/components/L/renderer/LRenderer.vue')['default']
    LTileLayer: typeof import('./src/components/L/components/LTileLayer.vue')['default']
    LToolTip: typeof import('./src/components/L/components/LToolTip.vue')['default']
    LWmsTileLayer: typeof import('./src/components/L/components/LWmsTileLayer.vue')['default']
    MenuList: typeof import('./src/components/MenuList/index.vue')['default']
    PreviewWord: typeof import('./src/components/PreviewWord/index.vue')['default']
    Renderer: typeof import('./src/components/L/renderer/index.vue')['default']
    TextScroll: typeof import('./src/components/TextScroll/index.vue')['default']
    TextScrollItem: typeof import('./src/components/TextScroll/TextScrollItem.vue')['default']
    VMessage: typeof import('./src/components/VMessage/index.vue')['default']
    VScroll: typeof import('./src/components/VScroll/index.vue')['default']
    VScrollItem: typeof import('./src/components/TextScroll/VScrollItem.vue')['default']
  }
}

export { }
