// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElMain: typeof import('element-plus/es')['ElMain']
    LBoundaryCanvas: typeof import('./src/components/L/plugins/LBoundaryCanvas.vue')['default']
    LConfigProvide: typeof import('./src/components/L/components/LConfigProvide.vue')['default']
    LFly: typeof import('./src/components/L/plugins/LFly.vue')['default']
    LFlyBounds: typeof import('./src/components/L/plugins/LFlyBounds.vue')['default']
    LFlyItem: typeof import('./src/components/L/plugins/LFlyItem.vue')['default']
    LFlyLatLng: typeof import('./src/components/L/plugins/LFlyLatLng.vue')['default']
    LFlyLatLngItem: typeof import('./src/components/L/plugins/LFlyLatLngItem.vue')['default']
    LIcon: typeof import('./src/components/L/components/LIcon.vue')['default']
    LLayerGroup: typeof import('./src/components/L/components/LLayerGroup.vue')['default']
    LMap: typeof import('./src/components/L/components/LMap.vue')['default']
    LMarker: typeof import('./src/components/L/components/LMarker.vue')['default']
    LPopup: typeof import('./src/components/L/components/LPopup.vue')['default']
    LTileLayer: typeof import('./src/components/L/components/LTileLayer.vue')['default']
    LToolTip: typeof import('./src/components/L/components/LToolTip.vue')['default']
    LWmsTileLayer: typeof import('./src/components/L/components/LWmsTileLayer.vue')['default']
    MenuList: typeof import('./src/components/MenuList/index.vue')['default']
  }
}

export { }
