// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElMain: typeof import('element-plus/es')['ElMain']
    LBoundaryCanvas: typeof import('./../components/L/plugins/LBoundaryCanvas.vue')['default']
    LConfigProvide: typeof import('./../components/L/components/LConfigProvide.vue')['default']
    LFeatureGroup: typeof import('./../components/L/components/LFeatureGroup.vue')['default']
    LFlyBounds: typeof import('./../components/L/plugins/LFlyBounds.vue')['default']
    LFlyLatLng: typeof import('./../components/L/plugins/LFlyLatLng.vue')['default']
    LGeoJson: typeof import('./../components/L/components/LGeoJson.vue')['default']
    LIcon: typeof import('./../components/L/components/LIcon.vue')['default']
    LLayerGroup: typeof import('./../components/L/components/LLayerGroup.vue')['default']
    LMap: typeof import('./../components/L/components/LMap.vue')['default']
    LMarker: typeof import('./../components/L/components/LMarker.vue')['default']
    LPopup: typeof import('./../components/L/components/LPopup.vue')['default']
    LTileLayer: typeof import('./../components/L/components/LTileLayer.vue')['default']
    LToolTip: typeof import('./../components/L/components/LToolTip.vue')['default']
    LWmsTileLayer: typeof import('./../components/L/components/LWmsTileLayer.vue')['default']
    MenuList: typeof import('./../components/MenuList/index.vue')['default']
    PreviewWord: typeof import('./../components/PreviewWord/index.vue')['default']
    TextScroll: typeof import('./../components/TextScroll/index.vue')['default']
    TextScrollItem: typeof import('./../components/TextScroll/TextScrollItem.vue')['default']
    VMessage: typeof import('./../components/VMessage/index.vue')['default']
  }
}

export { }
